### ISSUE TITLE
No CICD, makefile and license

### ISSUE THREAD

**Issue by thoriqsatriya** [AccelByte/justice-input-validation-go#1]
It would be better if we enable CICD using Travis for this repo. At least we run the linter and test in that pipeline. We can take a look at this file for reference: https://github.com/AccelByte/iam-go-sdk/blob/master/.travis.yml

In order to run `make test` we also need to create a Makefile. 

The other thing is, we need to add a license file.

**Comment by thoriqsatriya** [comment]
And I think it would be better if we put some examples of how to use this library and list of available rules in the readme

**Comment by anggorodewanto** [comment]
agreed

**Comment by fahribaharudin** [comment]
Working on it, thanks for the feedback.

**Comment by fahribaharudin** [comment]
I have enabled Travis CICD, create a Makefile, and write License on this repo 5db02a14741f786b2b67f068c7bff9047638caa8

**Comment by anggorodewanto** [comment]
Close this issue then
